name: Build and Test
on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build & Test with Gradle
      run: ./gradlew check

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: junit-test-results
        path: '**/build/test-results/*/TEST-*.xml'
        retention-days: 1

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/reports/kover
        retention-days: 1

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@27d65e188ec43221b20d26de30f4892fad91df2f
      if: always()
      with:
        check_name: Unit Tests
        files: |
          **/build/test-results/*/TEST-*.xml

    - name: Add coverage report to PR
      id: kover
      uses: mi-kas/kover-report@5f58465b6f395c8fa3adc2665e27250bad87de50
      with:
        path: |
          build/reports/kover/report.xml
        title: Code Coverage
        update-comment: true
